import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Builds technical indicators as features from the raw price data.
    """
    # Create a copy to avoid modifying the original dataframe
    data = df.copy()
    
    # Simple Moving Averages
    data['SMA_5'] = data['close'].rolling(window=5).mean()
    data['SMA_10'] = data['close'].rolling(window=10).mean()
    data['SMA_30'] = data['close'].rolling(window=30).mean()
    
    # Exponential Moving Averages
    data['EMA_10'] = data['close'].ewm(span=10, adjust=False).mean()
    
    # Relative Strength Index (RSI) - 14 days
    delta = data['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    data['RSI_14'] = 100 - (100 / (1 + rs))
    
    # MACD
    ema_12 = data['close'].ewm(span=12, adjust=False).mean()
    ema_26 = data['close'].ewm(span=26, adjust=False).mean()
    data['MACD'] = ema_12 - ema_26
    data['MACD_Signal'] = data['MACD'].ewm(span=9, adjust=False).mean()
    
    # Momentum (1 day returns)
    data['Return_1d'] = data['close'].pct_change()
    data['Return_5d'] = data['close'].pct_change(periods=5)
    
    # Volatility
    data['Volatility_10d'] = data['Return_1d'].rolling(window=10).std()
    
    # Drop NaNs generated by rolling functions
    data.dropna(inplace=True)
    
    return data

def prepare_targets(df: pd.DataFrame):
    """
    Prepares the targets for 5, 7, 30 days classification and 1 day regression.
    """
    data = df.copy()
    
    # 1-day exact price regression target (price of next day)
    data['Target_Reg_1d'] = data['close'].shift(-1)
    
    # Classification targets (1 for UP, 0 for DOWN)
    data['Target_Class_5d'] = (data['close'].shift(-5) > data['close']).astype(int)
    data['Target_Class_7d'] = (data['close'].shift(-7) > data['close']).astype(int)
    data['Target_Class_30d'] = (data['close'].shift(-30) > data['close']).astype(int)
    
    # Drop rows with NaN targets at the end of the dataset
    data.dropna(inplace=True)
    
    return data

def train_and_predict(df: pd.DataFrame):
    """
    Trains models and returns predictions for the most recent data point.
    """
    # 1. Build features
    featured_df = build_features(df)
    
    # Keep the last row for prediction (this doesn't have future targets)
    latest_data = featured_df.iloc[-1:]
    
    # 2. Prepare targets for training data
    # We use all data except the very end where targets cannot be computed
    train_df = prepare_targets(featured_df)
    
    features = [
        'open', 'high', 'low', 'close', 'volume', 
        'SMA_5', 'SMA_10', 'SMA_30', 'EMA_10', 
        'RSI_14', 'MACD', 'MACD_Signal', 
        'Return_1d', 'Return_5d', 'Volatility_10d'
    ]
    
    X = train_df[features]
    X_latest = latest_data[features]
    
    # Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_latest_scaled = scaler.transform(X_latest)
    
    # Initialize Models
    clf_5d = RandomForestClassifier(n_estimators=100, random_state=42)
    clf_7d = RandomForestClassifier(n_estimators=100, random_state=42)
    clf_30d = RandomForestClassifier(n_estimators=100, random_state=42)
    reg_1d = RandomForestRegressor(n_estimators=100, random_state=42)
    
    # Train Models
    clf_5d.fit(X_scaled, train_df['Target_Class_5d'])
    clf_7d.fit(X_scaled, train_df['Target_Class_7d'])
    clf_30d.fit(X_scaled, train_df['Target_Class_30d'])
    reg_1d.fit(X_scaled, train_df['Target_Reg_1d'])
    
    # Predict for the latest data point
    pred_5d = clf_5d.predict(X_latest_scaled)[0]
    prob_5d = clf_5d.predict_proba(X_latest_scaled)[0][1] # Probability of UP
    
    pred_7d = clf_7d.predict(X_latest_scaled)[0]
    prob_7d = clf_7d.predict_proba(X_latest_scaled)[0][1]
    
    pred_30d = clf_30d.predict(X_latest_scaled)[0]
    prob_30d = clf_30d.predict_proba(X_latest_scaled)[0][1]
    
    pred_price_1d = reg_1d.predict(X_latest_scaled)[0]
    
    current_price = latest_data['close'].iloc[0]
    
    return {
        "current_price": float(current_price),
        "prediction_1d_price": float(pred_price_1d),
        "classification_5d": "UP" if pred_5d == 1 else "DOWN",
        "confidence_5d": float(prob_5d if pred_5d == 1 else 1 - prob_5d),
        "classification_7d": "UP" if pred_7d == 1 else "DOWN",
        "confidence_7d": float(prob_7d if pred_7d == 1 else 1 - prob_7d),
        "classification_30d": "UP" if pred_30d == 1 else "DOWN",
        "confidence_30d": float(prob_30d if pred_30d == 1 else 1 - prob_30d)
    }
